### PR TITLE
Changed all occurrences of arduino.h to Arduino.h

### PR DESCRIPTION
**Pull request by cmcknight**
This change corrects for case-sensitive operating systems (Unix, Linux, OS X).

### CODE REVIEW

**Comment by Makeblock-official** [comment]
Thanks for you help, I have test the libraries on Linux, and it still can't be compiled. There have some BUG when looking for header files. Since we just release our mBlock for MACOS and windows with this libraries. We need more time to modified the code to support Linux. You can directly contact me email:  
myan@makeblock.cc

**Comment by cmcknight** [comment]
您好!

Can you forward build instructions and I’ll take a shot at getting it to build under Linux? Also, can you let me know when the 3.0 version of mBlock for Mac OS X will be released? It’s not appearing on the web site right now.

谢谢!

Charles McKnight

**Comment by Makeblock-official** [comment]
mBlock 3.1 version for MAC OS already released. you can get it from http://www.mblock.cc/

**Comment by cmcknight** [comment]
Hi,

Sorry to report that the Mac version on the website is still 2.2.1 (see below from http://www.mblock.cc/index.php?c=index&a=download <http://www.mblock.cc/index.php?c=index&a=download>).

	<script>
		function jump_down($arg)
		{
			if($arg==='win')
			{
				window.open("http://download.makeblock.cc/mblock/mBlock-setup_v3.0.0.zip");
			}else{
				window.open("http://download.makeblock.cc/mblock/macosx_v2.2.1.zip");
			}
//			setTimeout("location.href='http://www.mblock.cc/index.php?c=index&a=mbot'",5000);
		}
	</script>


You’ll need to update the website to make it available.

Best regards,

Charles

**Comment by Makeblock-official** [comment]
Hi, Charles,

I reconfirmed, MAC OS was released yesterday. So try again，you can get the latest version.

Thanks,
Mark

**Comment by cmcknight** [comment]
Hi Mark,

I checked the site last night and the link had been updated. 😄

Thanks!

Charles

**Pull request closed without merging**
